import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import "./../globals.css"
import SidebarLayout from '@/components/sidebar/sidebar_layout'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <div className='flex flex-row min-h-screen'>
          <SidebarLayout />
          <div className='flex-1 flex flex-col'>{children}</div>
        </div>
      </body>
    </html>
  )
}
